---
title: "Amazon Prime versus Netflix"
author: "Brian K. Liles"
date: "April 18, 2018"
output: html_document
---
#Assignment
Your task is to analyze an existing recommender system that you find interesting. 

#Introduction
After reading the article *Amazon.com Recommendations*, I decided to go a step further and delve into Amazon's Prime video service and their streaming competitor Netlix. 

**Who are your target users?**
Target users for these two streaming services are subscription holders to Amazon Prime and Netflix. Members of these services either pay a monthly fee, are receiving a free trial or obtaining the services through a specialized promotion. 

**What are their key goals?**
The key goals for these streaming services are to provide customers with a myriad of content they can watch on several devices. Both provide movies, comedy specials, documentaries and original programming. In order to maintain satisfied customers both use recommendation engines based on previous viewed content.

**How can you help them accomplish those goals?**
One of the issues I have with Amazon Prime is their polarizing recommendations. For example, I watched an original movie entitled **Crown Heights** about a wrongly convicted man who spent 21 years incarcerated. After viewing this movie I received a rash of criminal based straight-to-video recommendations. 

The difference with Netflix is that throughout the course of the subscribed month they provide the end-user with a listing of recently added content. This clearly gives Netflix the edge. Although both services provide the end-user with recommended content based on previous views, Netflix broadens the scope by providing more options which widens the recommendations.


Perform a Scenario Design analysis as described below.  Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers.

Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.

Include specific recommendations about how to improve the site's recommendation capabilities going forward. 

Create your report using an R Markdown file, and create a discussion thread with a link to the GitHub repo where your Markdown file notebook resides.  You are not expected to need to write code for this discussion assignment.

#Similar Analysis
A similar comparison can be found at the following site on **www.gadgetreview.com** - Netflix took the crown for being user friendly, device compatibility, number of titles, content, speed of service, quality, and least limitations. Amazon squeeked out victories in membership perks (clearly due to **Amazon.com**) and price.

#Conclusion
With Amazon clearly looking to corner every market deemed as a competitor I believe the corporate giant will make updates to their streaming service. One benefit with Prime over Netflix is Amazon's ability to stream music also. As far as original content Netflix is probably the closest to competiting with HBO. 

**Amazon** 
Improve recommendation engine by introducing new arrivals more often allowing end-users to broaden their viewing horizons.

**Netflix**
Bring back the sub-genres and align it with their bi-weekly recommendations.